---
include:
  - project: "saltbox/ci-lib"
    file: "build-image.yml"

  - project: "saltbox/ci-lib"
    file: "def-branch-merge-guard.yml"

  - project: "saltbox/ci-lib"
    file: "mirror-repo.yml"

stages:
  - test
  - build

Build Root Config image:
  extends: .build-image
  stage: test

Mirror Repository:
  extends: .mirror-repo
  stage: build
