---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


Build image for tag:
  extends: .build-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build image for branch:
  extends: .build-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'
